// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Analyzes a cryptocurrency pair using technical indicators and Gemini AI for trend predictions and recommendations.
 *
 * - analyzeCryptoPair - A function that initiates the cryptocurrency pair analysis.
 * - AnalyzeCryptoPairInput - The input type for the analyzeCryptoPair function.
 * - AnalyzeCryptoPairOutput - The return type for the analyzeCryptoPair function.
 */

import {ai} from '@/ai/genkit';
import { AnalyzeCryptoPairInputSchema, type AnalyzeCryptoPairInput, AnalyzeCryptoPairOutputSchema, type AnalyzeCryptoPairOutput } from '@/lib/types';
import { sendDiscordNotificationTool } from '@/lib/tools/discord-tool';


export async function analyzeCryptoPair(input: AnalyzeCryptoPairInput): Promise<AnalyzeCryptoPairOutput> {
  return analyzeCryptoPairFlow(input);
}

const analyzeCryptoPairPrompt = ai.definePrompt({
  name: 'analyzeCryptoPairPrompt',
  input: {schema: AnalyzeCryptoPairInputSchema},
  output: {schema: AnalyzeCryptoPairOutputSchema},
  tools: [sendDiscordNotificationTool],
  prompt: `Bạn là một chuyên gia phân tích kỹ thuật thị trường tiền mã hóa, đưa ra lời khuyên cho chế độ giao dịch: {{{mode}}}.
Dựa vào dữ liệu đầu vào cho cặp {{{pair}}} trên khung thời gian {{{timeframe}}}, hãy thực hiện một phân tích chi tiết.

**Dữ liệu đầu vào:**
- Giá hiện tại: {{{price}}}
- Giá cao nhất: {{{high}}}
- Giá thấp nhất: {{{low}}}
- **RSI (14):** {{{rsi}}}
- **MACD (12, 26, 9):**
    - Đường MACD: {{{macd.line}}}
    - Đường tín hiệu: {{{macd.signal}}}
- **EMA:**
    - EMA 9: {{{ema.ema9}}}
    - EMA 21: {{{ema.ema21}}}

**Thực hiện phân tích theo các bước sau, tùy chỉnh theo chế độ giao dịch '{{{mode}}}':**

1.  **Đánh giá tổng quan xu hướng:**
    - Phân tích xu hướng dựa trên các chỉ báo EMA, MACD, và RSI.
    - Kết hợp tất cả để đưa ra đánh giá chung (Tăng giá, Giảm giá, Đi ngang).

2.  **Giải thích các chỉ báo:**
    - 📈 **EMA:** Giá đang ở trên hay dưới các đường EMA? Có giao cắt vàng hay giao cắt tử thần không?
    - 📊 **MACD:** Biểu đồ histogram và vị trí các đường MACD cho thấy điều gì về động lượng?
    - 📉 **RSI:** RSI đang ở vùng nào (quá mua > 70, quá bán < 30, hay trung tính)?

3.  **Kết luận và Tín hiệu Giao dịch:**
    - Dựa trên phân tích tổng hợp, đưa ra kết luận cuối cùng: **MUA**, **BÁN**, hoặc **GIỮ**.

4.  **Kế hoạch Giao dịch Đề xuất (Tùy chỉnh theo chế độ '{{{mode}}}'):**
    - **Nếu là 'Scalping'**: Tập trung vào các mục tiêu ngắn hạn. Giá vào lệnh phải rất gần giá hiện tại. Dừng lỗ và Chốt lời phải rất chặt chẽ (ví dụ: 1-2% từ giá vào lệnh).
    - **Nếu là 'Swing'**: Tập trung vào các mục tiêu dài hạn hơn. Giá vào lệnh có thể ở một vùng rộng hơn. Dừng lỗ và Chốt lời sẽ dựa trên các mức hỗ trợ/kháng cự quan trọng trên biểu đồ.
    - **Giá vào lệnh:** Đề xuất một khoảng giá hợp lý.
    - **Dừng lỗ:** Đề xuất một mức dừng lỗ để bảo vệ vốn.
    - **Chốt lời:** Đề xuất các mức chốt lời tiềm năng.

5.  **Quản lý rủi ro:**
    - Cung cấp một lời khuyên ngắn gọn, súc tích về quản lý rủi ro, phù hợp với chế độ giao dịch đã chọn.

**Hành động cuối cùng:**
- Nếu có Discord Webhook URL được cung cấp ({{{discordWebhookUrl}}}), hãy sử dụng công cụ 'sendDiscordNotification' để gửi một thông báo tóm tắt.
- Ví dụ tin nhắn: "Tín hiệu mới cho {{{pair}}}: [Tín hiệu MUA/BÁN/GIỮ]. Chế độ: {{{mode}}}."
- Nếu không có URL, bỏ qua bước này.

**Yêu cầu:** Trả về kết quả bằng tiếng Việt, trình bày rõ ràng, dễ hiểu.`,
});

const analyzeCryptoPairFlow = ai.defineFlow(
  {
    name: 'analyzeCryptoPairFlow',
    inputSchema: AnalyzeCryptoPairInputSchema,
    outputSchema: AnalyzeCryptoPairOutputSchema,
  },
  async input => {
    const {output} = await analyzeCryptoPairPrompt(input);
    return output!;
  }
);
