// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Generates trading signals based on technical indicators.
 *
 * - generateTradingSignals - A function that initiates the trading signal generation.
 * - TradingSignalsInput - The input type for the generateTradingSignals function.
 * - TradingSignalsOutput - The return type for the generateTradingSignals function.
 */

import {ai} from '@/ai/genkit';
import {
  TradingSignalsInputSchema,
  type TradingSignalsInput,
  TradingSignalsOutputSchema,
  type TradingSignalsOutput,
} from '@/lib/types';


export async function generateTradingSignals(input: TradingSignalsInput): Promise<TradingSignalsOutput> {
  const simplifiedInput = {
    ...input,
    ema: input.ema.ema21, // Use EMA21 for the older prompt compatibility
    macd: input.macd.line, // Use MACD line for older prompt
  };
  return generateTradingSignalsFlow(simplifiedInput);
}

const generateTradingSignalsPrompt = ai.definePrompt({
  name: 'generateTradingSignalsPrompt',
  input: {schema: TradingSignalsInputSchema},
  output: {schema: TradingSignalsOutputSchema},
  prompt: `Bạn là một công cụ tạo tín hiệu giao dịch cho cặp tiền mã hóa {{{pair}}} trên khung thời gian {{{timeframe}}}.
Phân tích các giá trị chỉ báo kỹ thuật sau và tạo ra một danh sách tín hiệu giao dịch. Đối với mỗi chỉ báo, hãy cung cấp một tín hiệu rõ ràng "Mua", "Bán" hoặc "Trung tính", mức độ tự tin ("Cao", "Trung bình" hoặc "Thấp") và lý do ngắn gọn bằng tiếng Việt.

Giá hiện tại: {{{price}}}
- RSI (14): {{{rsi}}}
- MACD (12, 26, 9): {{{macd}}}
- EMA (21): {{{ema}}}

Tạo tín hiệu cho các chỉ báo sau:
1.  **RSI**: Tài sản đang bị quá mua (>70), quá bán (<30), hay trung tính?
2.  **MACD**: Đường MACD đang cắt lên trên đường tín hiệu (tăng giá), cắt xuống dưới (giảm giá), hay không có sự giao cắt rõ ràng? Xem xét vị trí của nó so với đường zero.
3.  **EMA và Giá**: Giá hiện tại đang ở trên đường EMA 21 (xu hướng tăng) hay ở dưới (xu hướng giảm)?
`,
});

const generateTradingSignalsFlow = ai.defineFlow(
  {
    name: 'generateTradingSignalsFlow',
    inputSchema: TradingSignalsInputSchema,
    outputSchema: TradingSignalsOutputSchema,
  },
  async (input) => {
    const {output} = await generateTradingSignalsPrompt(input);
    return output!;
  }
);
